General improvements

diff --git a/helpers/git-cloud-sync b/helpers/git-cloud-sync
--- a/helpers/git-cloud-sync
+++ b/helpers/git-cloud-sync
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/bash
 
 set -e
 
@@ -6,7 +6,7 @@ CONFDIR=$(git-cloud confdir)
 source "${CONFDIR}/config"
 source internal-git-cloud-connshare
 
-CONNSHARE="ask"
+CONNSHARE="auto"
 CONFIRMATION="yes"
 while [ 1 == 1 ]; do
     if [ "$1" == "--cs-ask" ]; then
@@ -79,6 +79,13 @@ if [ ! -e ./.git-cloud-root ]; then
     exit 1
 fi
 
+internal-git-cloud-load-keys
+setup_cloud_connshare "$RHOST" "$CONNSHARE"
+
+echo "=============================================="
+echo "====      Syncronizing repotrees         ====="
+echo "=============================================="
+
 echo
 echo "== Gathering local repos"
 
@@ -92,12 +99,10 @@ GIT_IDS=$(find . -not \( -path ./Trash -prune \) -name ".git" -prune | while rea
               echo "${ID}|${LPATH#./}"
           done)
 
-setup_cloud_connshare "$CONNSHARE"
-
 echo
 echo "== Gathering remote repos"
 
-GIT_SRC_IDS=$(exec_ssh -S "${GIT_CLOUD_SSHDIR}/connshare.socket" "$RHOST" bash -c 'true; set -e; cd "'"$RPATH"'"; if [ ! -e ./.git-cloud-remote-root ]; then echo "SAFTEY CHECK FAIL"; exit 0; fi; find . -type d -not \( -path ./Trash -prune \) -name "*.git" -prune | while read LINE; do
+GIT_SRC_IDS=$($GIT_SSH_COMMAND -S "${GIT_CLOUD_SSHDIR}/connshare.socket" "$RHOST" bash -c 'true; set -e; cd "'"$RPATH"'"; if [ ! -e ./.git-cloud-remote-root ]; then echo "SAFTEY CHECK FAIL"; exit 0; fi; find . -type d -not \( -path ./Trash -prune \) -name "*.git" -prune | while read LINE; do
                   if git --git-dir "${LINE}" show HEAD:.gituuid >& /dev/null; then
                       ID="$(git --git-dir "${LINE}" show HEAD:.gituuid)"
                   else
@@ -131,13 +136,13 @@ if grep -q '^SAFTEY CHECK FAIL$' <<< "$GIT_MOVE_COMMANDS"; then
     exit 1
 fi
 
-echo
-echo "= Local repo ids"
-echo "$GIT_IDS"
-echo
-echo "= Remote repo ids"
-echo "$GIT_SRC_IDS"
-echo
+#echo
+#echo "= Local repo ids"
+#echo "$GIT_IDS"
+#echo
+#echo "= Remote repo ids"
+#echo "$GIT_SRC_IDS"
+#echo
 
 CONFIRM_MOVE() {
     if [ "$CONFIRMATION" != "no" ]; then
@@ -275,11 +280,11 @@ while IFS= read -r LINE; do
             #if [ "${AUTOSYNC#$REMOTE}" != "${AUTOSYNC}" ]; then
             CONFIRM_SETURL "$LPATH" "${GIT_CLOUD_REMOTE_NAME}" "${REMOTE}/${LPATH}"
             #fi
-            MAIN_GIT_DIR=$(git -C "$LPATH" rev-parse --git-dir)
-            if [ ! -e "${MAIN_GIT_DIR}/worktrees/cloud" ]; then
-                echo "= Setting up snapshot worktree for $LPATH"
-                git -C "$LPATH" cloud snapshot
-            fi
+            #MAIN_GIT_DIR=$(git -C "$LPATH" rev-parse --git-dir)
+            #if [ ! -e "${MAIN_GIT_DIR}/worktrees/cloud" ]; then
+            #    echo "= Setting up snapshot worktree for $LPATH"
+            #    git -C "$LPATH" cloud snapshot
+            #fi
         else
             echo "Unexpected path error. The path:"
             echo "  $LPATH"
@@ -292,3 +297,22 @@ while IFS= read -r LINE; do
         fi
     fi
 done <<< "$GIT_SRC_IDS"
+
+echo "=============================================="
+echo "====      Syncronizing snapshots         ====="
+echo "=============================================="
+
+git-cloud-snaptree
+
+echo "=============================================="
+echo "====       Git pull in all repos         ====="
+echo "=============================================="
+
+git-cloud-pull
+
+echo "=============================================="
+echo "====           Snapshot status           ====="
+echo "=============================================="
+
+git-cloud-status
+
diff --git a/helpers/internal-git-cloud-connshare b/helpers/internal-git-cloud-connshare
--- a/helpers/internal-git-cloud-connshare
+++ b/helpers/internal-git-cloud-connshare
@@ -1,18 +1,47 @@
-setup_cloud_connshare() {
+if [ "$CONNSHARE_SETUP_DONE" != "1" ]; then
 
-CONNSHARE="$1"
+  CONFDIR=$(git-cloud confdir)
+  source "${CONFDIR}/config"
 
-if [ "$CONNSHARE" == "auto" -o "$CONNSHARE" == "ask" ]; then
+  setup_cloud_connshare() {
 
-  echo "== Setting up ssh connection sharing to remote (handle auth if asked)"
+    RHOST="$1"
+    CONNSHARE="$2"
+
+    if [ "$CONNSHARE" == "auto" -o "$CONNSHARE" == "ask" ]; then
+
+      if ssh -S "${GIT_CLOUD_SSHDIR}/%C.cs.socket" -O check "$RHOST" >& /dev/null; then
+          return
+      fi
+
+      echo "== Setting up ssh connection sharing to remote (handle auth if asked)"
+
+      if [ "$CONNSHARE" == "auto" ]; then
+          ssh -M -S "${GIT_CLOUD_SSHDIR}/%C.cs.socket" -o "ControlPersist=2h" "$RHOST" true
+          ls "${GIT_CLOUD_SSHDIR}/"
+      else
+          ssh -MM -S "${GIT_CLOUD_SSHDIR}/%C.cs.socket" -o "ControlPersist=2h" "$RHOST" true
+      fi
+
+      if ! ssh -S "${GIT_CLOUD_SSHDIR}/%C.cs.socket" -O check "$RHOST"; then
+          echo "Error: failed to open ssh connection with connection sharing to $RHOST"
+          exit 1
+      fi
+    fi
+  }
+
+  export GIT_SSH_COMMAND="ssh -S \"${GIT_CLOUD_SSHDIR}\"/%C.cs.socket"
 
   function trap_exit {
-      echo
-      echo "== Cleaning up ssh connection sharing socket"
-      if [ -e "${GIT_CLOUD_SSHDIR}/connshare.socket" ]; then
-          ssh -O exit -S "${GIT_CLOUD_SSHDIR}/connshare.socket" "$RHOST" hostname
-      fi
-      rm -f "${GIT_CLOUD_SSHDIR}/connshare.socket"
+        echo
+        echo "== Cleaning up ssh connection sharing sockets"
+        for SOCKET in "${GIT_CLOUD_SSHDIR}"/*.cs.socket; do
+            if [ "$SOCKET" == "${GIT_CLOUD_SSHDIR}/*.cs.socket" ]; then
+                break
+            fi
+            ssh -O exit -S "${SOCKET}" dummy
+            rm -f "${SOCKET}"
+        done
   }
   trap trap_exit EXIT
 
@@ -21,31 +50,6 @@ if [ "$CONNSHARE" == "auto" -o "$CONNSHARE" == "ask" ]; then
   }
   trap trap_ctrlc INT
 
-  if [ -e "${GIT_CLOUD_SSHDIR}/connshare.socket" ]; then
-      ssh -O exit -S "${GIT_CLOUD_SSHDIR}/connshare.socket" "$RHOST" hostname
-      rm -f "${GIT_CLOUD_SSHDIR}/connshare.socket"
-  fi
-
-  if [ "$CONNSHARE" == "auto" ]; then
-      ssh -M -S "${GIT_CLOUD_SSHDIR}/connshare.socket" -o "ControlPersist=2h" "$RHOST" true
-  else
-      ssh -S "${GIT_CLOUD_SSHDIR}/connshare.socket" -o "ControlPersist=2h" -o "ControlMaster=autoask" "$RHOST" true
-  fi
-
-  if ! ssh -S "${GIT_CLOUD_SSHDIR}/connshare.socket" -O check hostname; then
-      echo "Error: failed to open ssh connection with connection sharing to $RHOST"
-      exit 1
-  fi
-
-  export GIT_SSH_COMMAND="ssh -S '${GIT_CLOUD_SSHDIR}/connshare.socket'"
-  exec_ssh() {
-      ssh -S "${GIT_CLOUD_SSHDIR}/connshare.socket" "$@"
-  }
-else
-  exec_ssh() {
-      ssh "$@"
-  }
+  export -f setup_cloud_connshare
+  export CONNSHARE_SETUP_DONE=1
 fi
-
-
-}
